P0014 clean
Walkover-Web-Solution/proxy-ui pull request #106
Opened 2024-06-24 04:29 UTC by hemantkumargangwal

2024-06-24 04:59 UTC, rahul1choudhary requested changes
Please do discussed changes

2024-06-25 09:09 UTC, rakeshshrivas requested changes

2024-06-25 09:09 UTC, rakeshshrivas commented on apps/proxy/src/app/register/register.component.html
> +<div style="height: 100vh; background-color: #fafafa">
use class

2024-06-25 09:09 UTC, rakeshshrivas commented on apps/proxy/src/app/register/register.component.html
> +        style="box-shadow: rgba(0, 0, 0, 0.25) 0px 25px 50px -12px; background-color: #e6e6fa; width: 40%"
remove style

2024-06-25 09:09 UTC, rakeshshrivas commented on apps/proxy/src/app/register/register.component.html
> +        <h2 class="d-flex justify-content-center">Register</h2>
text-center

2024-06-25 09:09 UTC, rakeshshrivas commented on apps/proxy/src/app/register/register.component.html
> +                <div class="d-flex gap-3 mt-20">
remove margin mt-20 and add class `mt-4`

2024-06-25 10:05 UTC, rakeshshrivas requested changes

2024-06-26 05:13 UTC, rakeshshrivas requested changes

2024-06-26 06:49 UTC, rakeshshrivas requested changes

2024-06-26 06:49 UTC, rakeshshrivas commented on apps/proxy/src/app/register/register.component.html
> +    <mat-form-field appearance="outline" style="width: 100%">
class use class `w-100`

2024-06-26 06:49 UTC, rakeshshrivas commented on apps/proxy/src/styles.scss
> +    height: 61px;
remove height

2024-06-26 06:49 UTC, rakeshshrivas commented on apps/proxy/src/styles.scss
> +    width: 100%;
remove css

2024-06-26 08:10 UTC, rakeshshrivas approved these changes

2024-06-27 05:16 UTC, rahul1choudhary approved these changes

2024-06-27 05:18 UTC, merged