P0018 clean
Walkover-Web-Solution/proxy-ui pull request #120
Opened 2024-07-19 06:03 UTC by hemantkumargangwal

user login with password user can reset using otp

2024-07-19 08:33 UTC, rahul1choudhary requested changes

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +                type: 'email',
No Need to show form for email 
show mail as text and added option to change username

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +            [readonly]="type === 'email' && step === 3"
remove this

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.ts
> +        password: new FormControl<string | null>(null, [Validators.required]),
add proper pattern check

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.ts
> +        confirmPassword: new FormControl<string | null>(null, [Validators.required]),
Need to math password and confirmPassword
take ref of register page

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.store.ts
> +                            this.toast.success('login successful');
there is no toast in proxy-auth 
need to display error on screen like register

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +    <proxy-loader *ngIf="isLoading$ | async"></proxy-loader>
add loader on button instead of global loaders

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.ts
> +        if (this.loginForm.valid) {
these check will be remove if you use proxyMarkAllAsTouched properly

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/otp.module.ts
> +        UiPrimeNgToastModule,
we dont use toast in widget
remove it

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.html
> +<proxy-prime-ng-toast></proxy-prime-ng-toast>
remove this

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.ts
> +        this.otpWidgetService.showLogin$.pipe(filter(Boolean), takeUntil(this.destroy$)).subscribe((res) => {
use subject directly in HTML

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/service/otp-widget.service.ts
> +    showLogin$ = this.showlogin.asObservable();
no need of this

2024-07-19 08:33 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/service/otp-widget.service.ts
Missing handling for custom UI 
check `addButtonsToReferenceElement` this func

2024-07-19 08:43 UTC, rakeshshrivas requested changes

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +<div>
Remove Empty div

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +            <div>
Remove empty div if not required

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +        <div>
Remove empty div if not required

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +        <div>
Remove empty div if not required

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +    <mat-form-field appearance="outline" style="width: 100%">
use `w-100` class and remove inline style

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +            <button mat-flat-button color="primary" (click)="verfiyOtp()">Submit</button>
add loader on button

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.scss
> +    display: flex;
Remove style

2024-07-19 08:43 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/service/otp.service.ts
> +import { O } from '@angular/cdk/keycodes';
Remove import

2024-07-20 10:20 UTC, rahul1choudhary submitted a review, later dismissed

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.ts
> +                    } else if (buttonsData?.service_id === FeatureServiceIds.PasswordAuthentication) {
No Need of this 
For OTP it was done to add button after script is loaded

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.ts
> +    public showLogin = new BehaviorSubject<boolean>(false);
Use subject from service instead of creating new
it will give error for default UI

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.ts
> +import { F } from '@angular/cdk/keycodes';
why dont you check these useless imports before giving PR
Please review your PR thoroughly before asking for review

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.store.ts
> +    public apiError = new BehaviorSubject<string[]>(null);
data assigned but used in HTML 
and you can manage in it state also

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.ts
> +        if (this.loginForm.valid) {
not resolved

2024-07-20 10:20 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/component/login/login.component.ts
> +        email: new FormControl<string | null>({ value: null, disabled: true }, [
why are you managing email twice one in emailForm and second in resetPasswordForm
and type will be string only

2024-07-22 05:08 UTC, shubhamkeshari approved these changes

2024-07-22 06:12 UTC, rakeshshrivas requested changes

2024-07-22 06:12 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.html
> +    <div>
Please check

2024-07-22 06:12 UTC, rakeshshrivas commented on apps/proxy-auth/src/app/otp/component/login/login.component.scss
> +    gap: 20px;
gap 16px

2024-07-22 07:26 UTC, rakeshshrivas approved these changes

2024-07-22 07:45 UTC, merged

2024-07-23 03:50 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/send-otp/send-otp.component.ts
> +    public showLogin: boolean = false;
this was supposed to be mapped with service subject
`public showLogin: BehaviorSubject<boolean> = this.otpWidgetService.showlogin;`

2024-07-23 03:50 UTC, rahul1choudhary commented on apps/proxy-auth/src/app/otp/service/otp-widget.service.ts
> +    public showlogin = new BehaviorSubject<any>(false);
`public showlogin = new BehaviorSubject<boolean>(false);`